[phases.setup]
nixPkgs = ['nodejs_22', 'ruby_3_4', 'postgresql.dev', 'libyaml', 'gcc', 'gnumake', 'pkg-config', 'autoconf', 'automake', 'libtool']
nixLibs = ['libiconv', 'libffi', 'openssl', 'zlib', 'readline', 'gmp', 'libxml2', 'libxslt']

[phases.install]
cmds = [
    'corepack enable',
    'node --version && npm --version',
    'ruby --version && gem --version',
    'gem install bundler -v 2.3.11 --no-document',
    'cd backend && BUNDLE_SILENCE_ROOT_WARNING=1 bundle config --local deployment true',
    'cd backend && BUNDLE_SILENCE_ROOT_WARNING=1 bundle config --global build.nokogiri --use-system-libraries',
    'cd backend && BUNDLE_SILENCE_ROOT_WARNING=1 bundle config --global build.pg --with-pg-config=$(which pg_config)',
    'cd backend && BUNDLE_SILENCE_ROOT_WARNING=1 LIBRARY_PATH=/nix/store/$(ls /nix/store | grep "^[a-z0-9]*-libyaml-" | head -1)/lib CPATH=/nix/store/$(ls /nix/store | grep "^[a-z0-9]*-libyaml-" | head -1)/include bundle install --jobs 4 --retry 3',
    'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = [
    'echo "Starting build phase..."',
    'cd backend && bundle exec rails js:routes:typescript',
    'echo "TypeScript routes generated, building Next.js..."',
    'pnpm run build-next',
    'echo "Build completed successfully!"'
]

[start]
cmd = 'cd backend && bundle exec rails server -p $PORT -e $RAILS_ENV -b 0.0.0.0'

[variables]
NODE_ENV = 'production'
RAILS_ENV = 'production'
BUNDLE_SILENCE_ROOT_WARNING = '1'
MAKE = 'make'
CC = 'gcc'
PKG_CONFIG_PATH = '/nix/store/*-postgresql-*/lib/pkgconfig:/nix/store/*-libyaml-*/lib/pkgconfig'
