[phases.setup]
nixPkgs = ['nodejs_22', 'ruby_3_4', 'postgresql.dev', 'libyaml', 'gcc', 'gnumake', 'pkg-config', 'autoconf', 'automake', 'libtool']
nixLibs = ['libiconv', 'libffi', 'openssl', 'zlib', 'readline', 'gmp', 'libxml2', 'libxslt']

[phases.install]
cmds = [
    'corepack enable',
    'echo "=== System Versions ==="',
    'node --version && npm --version && ruby --version && gem --version',
    'echo "=== Installing Bundler 2.3.11 ==="',
    'gem install bundler -v 2.3.11 --no-document',
    'echo "=== Configuring Bundle ==="',
    'cd backend && bundle config --local deployment true',
    'cd backend && bundle config build.nokogiri --use-system-libraries',
    'cd backend && bundle config build.pg --with-pg-config=$(which pg_config)',
    'cd backend && bundle config build.psych --enable-bundled-libyaml',
    'echo "=== Installing Ruby Gems (PRODUCTION ONLY - NO DEV/TEST) ==="',
    'cd backend && bundle install --jobs 4 --retry 3 --without development test',
    'echo "=== Installing Node Packages ==="',
    'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = [
    'echo "Starting build phase..."',
    'cd backend && bundle exec rails js:routes:typescript',
    'echo "TypeScript routes generated, building Next.js..."',
    'pnpm run build-next',
    'echo "Build completed successfully!"'
]

[start]
cmd = 'cd backend && bundle exec rails server -p $PORT -e $RAILS_ENV -b 0.0.0.0'

[variables]
NODE_ENV = 'production'
RAILS_ENV = 'production'
BUNDLE_SILENCE_ROOT_WARNING = '1'
MAKE = 'make'
CC = 'gcc'
