---
EnableDefaultLinters: true
exclude:
  - "**/vendor/**/*" # For CI
  - "**/node_modules/**/*"
linters:
  AllowedScriptType:
    allowed_types:
      - 'text/javascript'
      - 'module'
  ErbSafety:
    enabled: true
  RequireInputAutocomplete:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/TrailingEmptyLines:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false