name: Build common setup

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2

    - uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: "pnpm"

    - run: pnpm i
      shell: bash

    - run: pnpm puppeteer browsers install chrome
      shell: bash

    - name: Cache Next build
      id: next-cache
      uses: actions/cache@v4
      with:
        path: frontend/.next/cache
        key: next-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml', 'backend/pnpm-lock.yaml', 'frontend/pnpm-lock.yaml') }}-${{ hashFiles('frontend/**/*.{ts,tsx}') }}
        restore-keys: |
          next-${{ runner.os }}-

    - run: cp .env.example .env && ln -s $PWD/.env ./frontend/.env
      shell: bash

    - uses: ruby/setup-ruby@v1
      with:
        working-directory: backend
        bundler-cache: true # runs "bundle install" and caches installed gems automatically
