name: Build common setup

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2

    - uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: "pnpm"

    - run: pnpm i
      shell: bash

    - name: Cache Puppeteer Chrome
      uses: actions/cache@v4
      with:
        path: ~/.cache/puppeteer
        key: puppeteer-chrome-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          puppeteer-chrome-${{ runner.os }}-

    - run: pnpm puppeteer browsers install chrome
      shell: bash

    - run: cp .env.example .env && ln -s $PWD/.env ./frontend/.env
      shell: bash

    - uses: ruby/setup-ruby@v1
      with:
        working-directory: backend
        bundler-cache: true # runs "bundle install" and caches installed gems automatically
