name: Build common setup

inputs:
  vercel-key:
    description: "Vercel key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check access
      shell: bash
      if: ${{ github.event.pull_request.author_association != 'MEMBER' && github.event.pull_request.author_association != 'OWNER' }}
      run: |
        echo "A member of the Antiwork organization must re-run this workflow manually."
        exit 1
    - uses: pnpm/action-setup@v2

    - uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: "pnpm"

    - run: pnpm i
      shell: bash

    - run: cp .env.example .env && ln -s $PWD/.env ./apps/next/.env
      shell: bash

    - uses: ruby/setup-ruby@v1
      with:
        working-directory: apps/rails
        bundler-cache: true # runs "bundle install" and caches installed gems automatically
