name: Build common setup

inputs:
  vercel-key:
    description: "Vercel key"
    required: true

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2

    - uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: "pnpm"

    - run: pnpm i
      shell: bash

    - run: pnpm vercel link --scope anti-work --yes --token ${{ inputs.vercel-key }} && pnpm vercel env pull .env --token ${{ inputs.vercel-key }} && ln -s $PWD/.env ./apps/next/.env
      shell: bash

    - uses: ruby/setup-ruby@v1
      with:
        working-directory: apps/rails
        bundler-cache: true # runs "bundle install" and caches installed gems automatically
