name: Build common setup

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2

    - uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: "pnpm"

    - run: pnpm i
      shell: bash

    - name: Cache Puppeteer Install
      id: puppeteer-install-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/puppeteer
        key: puppeteer-install-${{ runner.os }}-${{ hashFiles('backend/pnpm-lock.yaml', 'backend/package.json') }}
        restore-keys: |
          puppeteer-install-${{ runner.os }}-

    - run: pnpm puppeteer browsers install chrome
      if: steps.puppeteer-install-cache.outputs.cache-hit != 'true'
      shell: bash

    - run: cp .env.example .env && ln -s $PWD/.env ./frontend/.env
      shell: bash

    - uses: ruby/setup-ruby@v1
      with:
        working-directory: backend
        bundler-cache: true # runs "bundle install" and caches installed gems automatically
