# https://docs.docker.com/compose/compose-file/

services:
  db:
    image: postgres:16.3
    volumes:
      - flexilepgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flexile_development

  redis:
    image: redis:7.4.2
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - 6389:6379
    volumes:
      - ./tmp/redis:/data

  nginx:
    image: openresty/openresty:alpine-fat
    volumes:
      - ./flexile_dev.conf:/etc/nginx/conf.d/default.conf
      - ../certificates:/etc/ssl/certs/
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "/usr/local/openresty/luajit/bin/luarocks install lua-resty-http &&
            openresty -g 'daemon off;'"

volumes:
  flexilepgdata:
