name: autofix.ci

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ${{ github.repository == 'antiwork/flexile' && 'ubicloud-standard-2' || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v4

      - name: Build setup
        uses: ./.github/common/

      - run: pnpm run setup

      - run: bin/lint

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
