name: autofix.ci

on:
  pull_request_target:
permissions:
  contents: read

env:
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

concurrency:
  group: ${{ github.head_ref || github.ref }}-autofix
  cancel-in-progress: true

jobs:
  autofix:
    runs-on: ubicloud-standard-2

    steps:
      - uses: actions-cool/check-user-permission@7b90a27f92f3961b368376107661682c441f6103
        with:
          require: write
          username: ${{ github.triggering_actor }}
          error-if-missing: true

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build setup
        uses: ./.github/common/

      - run: pnpm run setup

      - run: bin/lint

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
