name: autofix.ci

on:
  pull_request_target:
permissions:
  contents: read

env:
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

concurrency:
  group: ${{ github.head_ref || github.ref }}-autofix
  cancel-in-progress: true

jobs:
  autofix:
    runs-on: ubicloud-standard-2

    steps:
      - name: Check access
        shell: bash
        if: ${{ github.event.pull_request.author_association != 'MEMBER' && github.event.pull_request.author_association != 'OWNER' }}
        run: |
          echo "A member of the Antiwork organization must re-run this workflow manually."
          exit 1

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build setup
        uses: ./.github/common/

      - run: pnpm run setup

      - run: bin/lint

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
