name: CI
on:
  push:
    branches:
      - main
  pull_request_target:
permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.ref }}-ci
  cancel-in-progress: ${{ !!github.head_ref }}

env:
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
  RAILS_ENV: test
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  WISE_API_KEY: ${{ secrets.WISE_API_KEY }}
  WISE_PROFILE_ID: ${{ secrets.WISE_PROFILE_ID }}

jobs:
  rspec:
    runs-on: ubicloud-standard-2

    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: flexile_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:6.2.3
        ports:
          - 6389:6379
        options: --entrypoint redis-server

    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [2]
        ci_node_index: [0, 1]

    steps:
      - uses: actions-cool/check-user-permission@7b90a27f92f3961b368376107661682c441f6103
        with:
          require: write
          username: ${{ github.triggering_actor }}
          error-if-missing: true

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build setup
        uses: ./.github/common/

      - name: Setup test database
        run: cd apps/rails && bundle exec rails db:create db:schema:load

      - name: Run tests
        env:
          RUBY_YJIT_ENABLE: 1
          KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC: ${{ secrets.KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC }}
          KNAPSACK_PRO_CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          KNAPSACK_PRO_CI_NODE_INDEX: ${{ matrix.ci_node_index }}
          KNAPSACK_PRO_LOG_LEVEL: info
        run: cd apps/rails && bundle exec rake "knapsack_pro:queue:rspec[--format RSpec::Github::Formatter --tag ~skip --tag ~type:system --format progress]"
        timeout-minutes: 20

  playwright:
    name: Tests (${{ matrix.shardIndex }}/${{ matrix.shardTotal }})
    runs-on: ubicloud-standard-2
    strategy:
      fail-fast: false
      matrix:
        shardTotal: [5]
        shardIndex: [1, 2, 3, 4, 5]

    steps:
      - uses: actions-cool/check-user-permission@7b90a27f92f3961b368376107661682c441f6103
        with:
          require: write
          username: ${{ github.triggering_actor }}
          error-if-missing: true

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build setup
        uses: ./.github/common/

      - run: node docker/createCertificate.js

      - name: Run docker compose
        run: docker compose -f docker/docker-compose-local-linux.yml up -d

      - run: NODE_ENV=test pnpm run build-next --no-lint
        shell: bash

      - name: Install foreman
        run: gem install foreman

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Run Playwright tests
        run: pnpm playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.shardIndex }}
          path: playwright-report/
          retention-days: 7
