name: Rspec CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.ref }}-rspec
  cancel-in-progress: ${{ !github.head_ref }}

env:
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
  RAILS_ENV: test
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  WISE_API_KEY: ${{ secrets.WISE_API_KEY }}
  WISE_PROFILE_ID: ${{ secrets.WISE_PROFILE_ID }}

jobs:
  rspec:
    name: Tests
    runs-on: ubicloud-standard-2

    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: flexile_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:6.2.3
        ports:
          - 6389:6379
        options: --entrypoint redis-server

    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [2]
        ci_node_index: [0, 1]

    steps:
      - name: Check access
        shell: bash
        if: ${{ github.event.pull_request.author_association != 'MEMBER' && github.event.pull_request.author_association != 'OWNER' }}
        run: |
          echo "A member of the Antiwork organization must re-run this workflow manually."
          exit 1

      - uses: actions/checkout@v4

      - name: Build setup
        uses: ./.github/common/

      - name: Setup test database
        run: cd apps/rails && bundle exec rails db:create db:schema:load

      - name: Run tests
        env:
          RUBY_YJIT_ENABLE: 1
          KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC: ${{ secrets.KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC }}
          KNAPSACK_PRO_CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          KNAPSACK_PRO_CI_NODE_INDEX: ${{ matrix.ci_node_index }}
          KNAPSACK_PRO_LOG_LEVEL: info
        run: cd apps/rails && bundle exec rake "knapsack_pro:queue:rspec[--format RSpec::Github::Formatter --tag ~skip --tag ~type:system --format progress]"
        timeout-minutes: 20
