name: Playwright CI
on: push

# Cancel builds for previous commits on the same branch unless the branch is "main"
concurrency:
  group: ${{ github.ref }}-playwright
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  playwright:
    name: Tests (${{ matrix.shardIndex }}/${{ matrix.shardTotal }})
    runs-on: ubicloud-standard-2
    strategy:
      fail-fast: false
      matrix:
        shardTotal: [5]
        shardIndex: [1, 2, 3, 4, 5]

    steps:
      - uses: actions/checkout@v4

      - name: Build setup
        uses: ./.github/common/
        with:
          vercel-key: ${{ secrets.VERCEL_ENV_KEY }}

      - run: node docker/createCertificate.js

      - name: Run docker compose
        run: docker compose -f docker/docker-compose-local-linux.yml up -d

      - run: NODE_ENV=test pnpm run build-next --no-lint
        shell: bash

      - name: Install foreman
        run: gem install foreman

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Run Playwright tests
        run: pnpm playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.shardIndex }}
          path: playwright-report/
          retention-days: 7
